/**
 * Accounts engine — RRSP/RRIF, TFSA, and non-registered mechanics. Pure functions, no React/IO.
 *
 * Growth, withdrawals, RRIF mandatory minimums + withholding, and the per-income-type taxable
 * amounts for non-registered accounts. The projection loop composes these each year; the tax
 * module turns the taxable amounts here into tax owed. See plan §6 / edge-cases §5.
 */

import { RRIF_FACTORS_2026, rrifFactor, type RrifFactorConfig } from '../config/rrif-factors';
import { LIF_FACTORS_2026, lifMaxFactor, type LifFactorConfig } from '../config/lif-factors';
import { ACCOUNTS_CONFIG_2026, type AccountsConfig } from './config';

export { rrifFactor, lifMaxFactor };

/**
 * LIF MAXIMUM withdrawal for the year = Jan-1 balance × the federal LIF max factor for the age. A LIF
 * also has the RRIF minimum as a floor (`rrifMinimum`); the LIF max is the ceiling a RRIF lacks.
 */
export function lifMaximum(jan1Balance: number, age: number, cfg: LifFactorConfig = LIF_FACTORS_2026): number {
  return jan1Balance * lifMaxFactor(age, cfg);
}

/** Grow a balance by one year's return. `returnRate` is a fraction (0.05 = 5%). */
export function growAccount(balance: number, returnRate: number): number {
  return balance * (1 + returnRate);
}

/** Apply a withdrawal, clamped so you can't draw more than the balance (or a negative amount). */
export function applyWithdrawal(balance: number, requested: number): { balance: number; withdrawn: number } {
  const withdrawn = Math.min(Math.max(requested, 0), Math.max(balance, 0));
  return { balance: balance - withdrawn, withdrawn };
}

/**
 * RRIF mandatory minimum withdrawal = Jan-1 balance × age factor. Fully taxable.
 * There is NO minimum in the year the RRIF is opened (`isOpeningYear`), so it returns 0 then.
 * `age` is the holder's age at the start of the year (or the younger spouse's age if that
 * election was made — pass whichever age the factor should key off).
 */
export function rrifMinimum(
  jan1Balance: number,
  age: number,
  opts: { isOpeningYear?: boolean } = {},
  cfg: RrifFactorConfig = RRIF_FACTORS_2026,
): number {
  if (opts.isOpeningYear) return 0;
  return jan1Balance * rrifFactor(age, cfg);
}

/**
 * Withholding tax on a RRIF/RRSP withdrawal. NONE is withheld on the mandatory minimum; the
 * tiered rate applies only to the amount ABOVE the minimum, as a single rate on that whole
 * over-minimum amount. This is a prepayment credited on the return — model it separately from
 * tax owed, never add it to tax.
 *
 *   ≤ $5,000 over → 10% · $5,000.01–$15,000 over → 20% · > $15,000 over → 30%
 */
export function rrifWithholding(amountOverMinimum: number, cfg: AccountsConfig = ACCOUNTS_CONFIG_2026): number {
  const over = Math.max(amountOverMinimum, 0);
  if (over === 0) return 0;
  const { upTo5k, upTo15k, over15k } = cfg.withholding;
  const rate = over <= 5_000 ? upTo5k : over <= 15_000 ? upTo15k : over15k;
  return over * rate;
}

/** Taxable income generated by a non-registered withdrawal/realization, split by income type. */
export function interestTaxableAmount(interest: number): number {
  return interest; // fully taxable at the marginal rate
}
export function eligibleDividendTaxableAmount(cashDividend: number, cfg: AccountsConfig = ACCOUNTS_CONFIG_2026): number {
  return cashDividend * (1 + cfg.eligibleDividendGrossUp); // grossed-up amount enters income; DTC applied in tax module
}
export function capitalGainTaxableAmount(realizedGain: number, cfg: AccountsConfig = ACCOUNTS_CONFIG_2026): number {
  return Math.max(realizedGain, 0) * cfg.capitalGainsInclusion; // only realized gains; 50% inclusion
}

/**
 * A TFSA withdrawal: tax-free and EXCLUDED from net income — so it never adds to taxable income
 * and never counts toward the OAS clawback / GIS thresholds. Returned explicitly so callers can't
 * accidentally tax it. (Re-contribution room is restored the following calendar year — modelled elsewhere.)
 */
export function tfsaWithdrawal(amount: number): { cash: number; taxableIncome: 0; netIncomeImpact: 0 } {
  return { cash: Math.max(amount, 0), taxableIncome: 0, netIncomeImpact: 0 };
}
